// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ4fSCEYAEcafVfxjIKWVEWc98bYf0Nis',
    appId: '1:617657292962:web:de97ff2a42456bea405ffb',
    messagingSenderId: '617657292962',
    projectId: 'myapp-d8384',
    authDomain: 'myapp-d8384.firebaseapp.com',
    storageBucket: 'myapp-d8384.appspot.com',
    measurementId: 'G-FW0C61H6ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrgI1OYrcGTC3GpaQhIVy8xzCulpm4IGs',
    appId: '1:617657292962:android:1506e98905c259ad405ffb',
    messagingSenderId: '617657292962',
    projectId: 'myapp-d8384',
    storageBucket: 'myapp-d8384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5klHCeE9_RkFI7CEFb8PL-pLFCk7QGok',
    appId: '1:617657292962:ios:54f42b2bc1e1cce1405ffb',
    messagingSenderId: '617657292962',
    projectId: 'myapp-d8384',
    storageBucket: 'myapp-d8384.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5klHCeE9_RkFI7CEFb8PL-pLFCk7QGok',
    appId: '1:617657292962:ios:54f42b2bc1e1cce1405ffb',
    messagingSenderId: '617657292962',
    projectId: 'myapp-d8384',
    storageBucket: 'myapp-d8384.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ4fSCEYAEcafVfxjIKWVEWc98bYf0Nis',
    appId: '1:617657292962:web:13992404e6fec6ac405ffb',
    messagingSenderId: '617657292962',
    projectId: 'myapp-d8384',
    authDomain: 'myapp-d8384.firebaseapp.com',
    storageBucket: 'myapp-d8384.appspot.com',
    measurementId: 'G-0W1C2P2JTN',
  );
}
